<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" />
        <PackageReference Include="Mediator.SourceGenerator">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mycelium.Api.Auth\Mycelium.Api.Auth.csproj" />
        <ProjectReference Include="..\Mycelium.Api.Core\Mycelium.Api.Core.csproj" />
        <ProjectReference Include="..\Mycelium.Api.Devices\Mycelium.Api.Devices.csproj" />
        <ProjectReference Include="..\Mycelium.Api.EntityFramework\Mycelium.Api.EntityFramework.csproj" />
        <ProjectReference Include="..\Mycelium.Api.Organisations\Mycelium.Api.Organisations.csproj" />
        <ProjectReference Include="..\Mycelium.Api.Users\Mycelium.Api.Users.csproj" />
        <ProjectReference Include="..\Mycelium.Common\Mycelium.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
